### ISSUE TITLE
scrapecalaccesscandidates crashing with this error

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-processed-data#12]
```
Processing 68 elections.
  Processing 2016 GENERAL
Traceback (most recent call last):
  File "example/manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ben/.virtualenvs/django-calaccess-processed-data/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/ben/.virtualenvs/django-calaccess-processed-data/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ben/.virtualenvs/django-calaccess-processed-data/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ben/.virtualenvs/django-calaccess-processed-data/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/ben/Code/django-calaccess-processed-data/calaccess_processed/management/commands/__init__.py", line 90, in handle
    self.process_results(results)
  File "/home/ben/Code/django-calaccess-processed-data/calaccess_processed/management/commands/scrapecalaccesscandidates.py", line 127, in process_results
    election_id=d['scraped_id'],
KeyError: 'scraped_id'
```

**Comment by sahilchinoy** [comment]
This should be fixed in the latest commit.
