### ISSUE TITLE
Error thrown by mergeocdpersonsbycontestandname

### ISSUE THREAD

**Issue by gordonje** [california-civic-data-coalition/django-calaccess-processed-data#129]
From this morning's update attempt on the dev server:
```
ERROR|03/Aug/2017 13:53:18|manage|Admin Command Error: /apps/calaccess/repo/manage.py updatedownloadswebsite --noinput --publish --verbosity=3
Traceback (most recent call last):
  File "/apps/calaccess/repo/manage.py", line 35, in <module>
    execute_from_command_line(sys.argv)
  File "/apps/calaccess/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/apps/calaccess/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/apps/calaccess/lib/python2.7/site-packages/django/core/management/base.py", line 305, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/apps/calaccess/lib/python2.7/site-packages/django/core/management/base.py", line 356, in execute
    output = self.handle(*args, **options)
  File "/apps/calaccess/repo/calaccess_website/management/commands/updatedownloadswebsite.py", line 37, in handle
    call_command('processcalaccessdata')
  File "/apps/calaccess/lib/python2.7/site-packages/django/core/management/__init__.py", line 130, in call_command
    return command.execute(*args, **defaults)
  File "/apps/calaccess/lib/python2.7/site-packages/django/core/management/base.py", line 356, in execute
    output = self.handle(*args, **options)
  File "/apps/calaccess/lib/python2.7/site-packages/calaccess_processed/management/commands/processcalaccessdata.py", line 64, in handle
    self.load()
  File "/apps/calaccess/lib/python2.7/site-packages/calaccess_processed/management/commands/processcalaccessdata.py", line 92, in load
    no_color=self.no_color,
  File "/apps/calaccess/lib/python2.7/site-packages/django/core/management/__init__.py", line 130, in call_command
    return command.execute(*args, **defaults)
  File "/apps/calaccess/lib/python2.7/site-packages/django/core/management/base.py", line 356, in execute
    output = self.handle(*args, **options)
  File "/apps/calaccess/lib/python2.7/site-packages/calaccess_processed/management/commands/loadocdelections.py", line 29, in handle
    self.load()
  File "/apps/calaccess/lib/python2.7/site-packages/calaccess_processed/management/commands/loadocdelections.py", line 89, in load
    call_command('mergeocdpersonsbycontestandname', **options)
  File "/apps/calaccess/lib/python2.7/site-packages/django/core/management/__init__.py", line 130, in call_command
    return command.execute(*args, **defaults)
  File "/apps/calaccess/lib/python2.7/site-packages/django/core/management/base.py", line 356, in execute
    output = self.handle(*args, **options)
  File "/apps/calaccess/lib/python2.7/site-packages/calaccess_processed/management/commands/mergeocdpersonsbycontestandname.py", line 35, in handle
    self.handle_group(group_q)
  File "/apps/calaccess/lib/python2.7/site-packages/calaccess_processed/management/commands/mergeocdpersonsbycontestandname.py", line 143, in handle_group
    OCDPersonProxy.objects.merge([c.person for c in group_q.all()])
  File "/apps/calaccess/lib/python2.7/site-packages/calaccess_processed/models/proxies/opencivicdata/people.py", line 73, in merge
    merge(keep, i)
  File "/apps/calaccess/src/opencivicdata/opencivicdata/merge.py", line 128, in merge
    diff = compute_diff(obj1, obj2)
  File "/apps/calaccess/src/opencivicdata/opencivicdata/merge.py", line 22, in compute_diff
    raise ValueError('cannot merge object with itself')
```

This is the error that's popped here and there but we've never fully trapped. It seems to occur when `mergeocdpersonsbycontestandname` is used after the initial data load.

**Comment by gordonje** [comment]
A little more detail...

Starting with empty OCD tables, I...
1. Called `loadocdelections`, which completed without throwing any errors.
2. Called `mergeocdpersonsbycontestandname`, which did not try to merge anyone and did not throw any errors.
3. I then called `loadocdelections` again, and this time the merge command threw the above error.
4. Now whenever I call `mergeocdpersonsbycontestandname`, I get this error.

So one of the other upstream commands in `loadocdelections` must also be a factor. I'm looking at you `loadocdcandidaciesfrom501s`.

**Comment by gordonje** [comment]
The merge we're attempting when this error is thrown is BRIAN DAHLE in the ASSEMBLY 01 race in the 2016 GENERAL.

However, this merge shouldn't even be happening. There are only two candidacy records for this contest, and only one of them is named BRIAN DAHLE:
```sql
select 
    c.candidate_name, p.name, c.extras, c.registration_status, c.person_id, c.party_id, *
from opencivicdata_candidacy c
join opencivicdata_candidatecontest cc
on cc.id = c.contest_id
join opencivicdata_election e
on e.id = cc.election_id
join opencivicdata_person p
on p.id = c.person_id
where e.name = '2016 GENERAL'
and cc.name = 'ASSEMBLY 01';
```

**Comment by gordonje** [comment]
With a little extra logging, it looks like the merge is being attempted because of grouping by person other names.

**Comment by gordonje** [comment]
So it seems like there are actually two issues here:
1. The query generated in the `.group_by_other_name()` method on `mergeocdpersonsbycontestandname` should counting the number of distinct person_ids that share the same other_name, but isn't.
2. Somewhere we are inserting duplicate `opencivicdata_person` records with the same `person_id` and `name` values.

**Comment by gordonje** [comment]
As for the first issue, this is the query currently generated by the Django queryset:
```sql
SELECT 
    "opencivicdata_personname"."name", 
    COUNT("opencivicdata_candidacy"."id") AS "row_count" 
FROM "opencivicdata_candidacy" 
INNER JOIN "opencivicdata_person" 
ON ("opencivicdata_candidacy"."person_id" = "opencivicdata_person"."id") 
LEFT OUTER JOIN "opencivicdata_personname" 
ON ("opencivicdata_person"."id" = "opencivicdata_personname"."person_id") 
WHERE "opencivicdata_candidacy"."contest_id" = ocd-contest/fb5e994b-ed61-44dd-b554-59847b4e2e94 
GROUP BY "opencivicdata_personname"."name" 
HAVING COUNT("opencivicdata_candidacy"."id") > 1;
```

But I think this is the query we want:
```sql
SELECT 
    "opencivicdata_personname"."name", 
    COUNT(DISTINCT "opencivicdata_candidacy"."person_id") AS "row_count" 
FROM "opencivicdata_candidacy" 
INNER JOIN "opencivicdata_person" 
ON ("opencivicdata_candidacy"."person_id" = "opencivicdata_person"."id") 
LEFT OUTER JOIN "opencivicdata_personname" 
ON ("opencivicdata_person"."id" = "opencivicdata_personname"."person_id") 
WHERE "opencivicdata_candidacy"."contest_id" = 'ocd-contest/fb5e994b-ed61-44dd-b554-59847b4e2e94'
GROUP BY "opencivicdata_personname"."name"
HAVING COUNT(DISTINCT "opencivicdata_candidacy"."person_id") > 1;
```

**Comment by gordonje** [comment]
Think I solved the distinct count issue.

However, when I re-ran `loadocdelections` I got the same error because now there are two candidates in a contest with the same person_id: 
```sql
select 
    c.candidate_name, p.name, c.extras, c.registration_status, c.person_id, c.party_id, *
from opencivicdata_candidacy c
join opencivicdata_candidatecontest cc
on cc.id = c.contest_id
join opencivicdata_election e
on e.id = cc.election_id
join opencivicdata_person p
on p.id = c.person_id
where e.name = '2014 GENERAL'
and cc.name = 'ASSEMBLY 06';
```

It's BRIAN CAPLES in the Assembly 06 in the 2014 General.

**Comment by gordonje** [comment]
Caples is in our corrections file for this race. Wonder if that's a factor...

**Comment by gordonje** [comment]
Re: the duplicate other name records...

This doesn't happen on the initial load of data. Actually, we only end up with 9 `opencivicdata_personname` records after the first run of `loadocdelections`.

**Comment by gordonje** [comment]
### First run of `loadocdelections`:
* no errors
```
+--------------------------------+-------------+
| table                          | row_count   |
|--------------------------------+-------------|
| candidacy                      | 5890        |
| candidacysource                | 5890        |
| personname                     | 9           |
+--------------------------------+-------------+
```

### Second run, no errors:
* no errors
* Loading additional candidacies from Form 501 filings
	* Processing Form 501: 728403
```
+--------------------------------+-------------+
| table                          | row_count   |
|--------------------------------+-------------|
| candidacy                      | 5890        |
| candidacysource                | 5890        |
| personname                     | 3545        |
+--------------------------------+-------------+
```

### Third run:
* Loading additional candidacies from Form 501 filings
	* Processing Form 501: 728403
* Loading Candidate Contests
	* Created Candidacy: BRIAN CAPLES in Assembly 06
	* Created Candidacy: BRIAN CAPLES in Assembly 06
* Merging 2 persons in ASSEMBLY 06 (in 2014 GENERAL)
 - BRIAN CAPLES (ocd-person/adde3938-15bc-4766-b5f7-f1d144f005bd)
 - BRIAN CAPLES (ocd-person/adde3938-15bc-4766-b5f7-f1d144f005bd)
* Then an error 
```
+--------------------------------+-------------+
| table                          | row_count   |
|--------------------------------+-------------|
| candidacy                      | 5892        | 
| candidacysource                | 5892        | 
| personname                     | 7081        | 
+--------------------------------+-------------+
```

### Suspects:
* `.add_other_name()` on `OCDPersonProxy`, which is called:
	* In `.get_or_create_from_calaccess()` on `OCDPersonManager` 
	* In two different places on `.get_or_create_from_calaccess()` on `OCDCandidacyManager`
* `.update_name()` on `OCDPersonProxy`, which is called in `.get_or_create_from_calaccess()` on `OCDCandidacyManager`.

**Comment by gordonje** [comment]
Need to keep an eye on deltas to `opencivicdata_candidatecontest` as well.

**Comment by palewire** [comment]
I believe this has been settled.
