### ISSUE TITLE
jsonb error from PostgreSQL when loading OCD filings

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-processed-data#194]
Does this mean something is off with my PostgreSQL install?

```bash
$ python example/manage.py loadocdfilingsfrom460s
Loading data extracted from Form 460 filings
Traceback (most recent call last):
  File "example/manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ben/.virtualenvs/django-calaccess-processed-data/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/ben/.virtualenvs/django-calaccess-processed-data/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ben/.virtualenvs/django-calaccess-processed-data/local/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ben/.virtualenvs/django-calaccess-processed-data/local/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "calaccess_processed/management/commands/loadocdfilingsfrom460s.py", line 37, in handle
    OCDCommitteeProxy.objects.load_form460_data()
  File "calaccess_processed/models/proxies/opencivicdata/campaign_finance/committees.py", line 33, in load_form460_data
    execute_custom_sql('insert_committees_from_form460s')
  File "calaccess_processed/sql/__init__.py", line 82, in execute_custom_sql
    cursor.execute(composed_sql, params)
  File "/home/ben/.virtualenvs/django-calaccess-processed-data/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/ben/.virtualenvs/django-calaccess-processed-data/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/ben/.virtualenvs/django-calaccess-processed-data/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/ben/.virtualenvs/django-calaccess-processed-data/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: column "extras" is of type jsonb but expression is of type json
LINE 21:     ('{"calaccess_filer_id":' || f460.filer_id || '}')::json...
              ^
HINT:  You will need to rewrite or cast the expression.
```

**Comment by gordonje** [comment]
Hmmm...I have not seen this error. I'm running postgres 9.6.1 locally:
```sql
select version()
```
```
+----------------------------------------------------------------------------------------------------------------+
| version                                                                                                        |
|----------------------------------------------------------------------------------------------------------------|
| PostgreSQL 9.6.1 on x86_64-apple-darwin15.6.0, compiled by Apple LLVM version 8.0.0 (clang-800.0.42.1), 64-bit |
+----------------------------------------------------------------------------------------------------------------+
```

We should probably just cast as jsonb here (and in other SQL scripts), since this is the data type Django uses for the [JSONField](https://docs.djangoproject.com/en/1.11/ref/contrib/postgres/fields/#jsonfield).

Will push up that change.

**Comment by palewire** [comment]
```calaccess_website=# select version();```
```
                                                    version                                                    
---------------------------------------------------------------------------------------------------------------
 PostgreSQL 9.4.7 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010, 64-bit
(1 row)
```
