### ISSUE TITLE
Migration issue

### ISSUE THREAD

**Issue by gordonje** [california-civic-data-coalition/django-calaccess-processed-data#22]
Looks like a missing dependency from calaccess_raw or a link between the two:

```
Traceback (most recent call last):
  File "example/manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/gordo/.virtualenvs/django-calaccess-processed-data/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/gordo/.virtualenvs/django-calaccess-processed-data/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/gordo/.virtualenvs/django-calaccess-processed-data/lib/python2.7/site-packages/django/core/management/base.py", line 305, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/gordo/.virtualenvs/django-calaccess-processed-data/lib/python2.7/site-packages/django/core/management/base.py", line 356, in execute
    output = self.handle(*args, **options)
  File "/Users/gordo/.virtualenvs/django-calaccess-processed-data/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 83, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/Users/gordo/.virtualenvs/django-calaccess-processed-data/lib/python2.7/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/Users/gordo/.virtualenvs/django-calaccess-processed-data/lib/python2.7/site-packages/django/db/migrations/loader.py", line 52, in __init__
    self.build_graph()
  File "/Users/gordo/.virtualenvs/django-calaccess-processed-data/lib/python2.7/site-packages/django/db/migrations/loader.py", line 268, in build_graph
    raise exc
django.db.migrations.exceptions.NodeNotFoundError: Migration calaccess_processed.0001_initial dependencies reference nonexistent parent node (u'calaccess_raw', u'0008_auto_20161122_0227')
```

**Comment by gordonje** [comment]
Think I fixed this by updating to the latest version of `django-calaccess-raw-data` and deleting all migrations, running the initial calaccess_raw migration, making and running the initial calaccess_processed migration.

**Comment by palewire** [comment]
![giphy](https://cloud.githubusercontent.com/assets/9993/20680816/834e318c-b555-11e6-92cd-1dc66803d525.gif)

**Comment by gordonje** [comment]
Certainly don't mind seeing Ray Allen get knocked around on repeat.
