### ISSUE TITLE
load filings crash

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-processed-data#238]
```bash
Loading calaccess_processed_form460scheduleaitemversion
Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/home/palewire/.virtualenvs/django-calaccess-processed-data/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/palewire/.virtualenvs/django-calaccess-processed-data/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/palewire/.virtualenvs/django-calaccess-processed-data/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/palewire/.virtualenvs/django-calaccess-processed-data/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "calaccess_processed/management/commands/loadcalaccessfilings.py", line 67, in handle
    self.handle_models('version')
  File "calaccess_processed/management/commands/loadcalaccessfilings.py", line 78, in handle_models
    self.load_model_list(model_list)
  File "calaccess_processed/management/commands/loadcalaccessfilings.py", line 145, in load_model_list
    m.objects.load()
  File "calaccess_processed/managers/bulkloadsql.py", line 35, in load
    self.execute()
  File "calaccess_processed/managers/bulkloadsql.py", line 46, in execute
    c.execute(self.sql)
  File "/home/palewire/.virtualenvs/django-calaccess-processed-data/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/palewire/.virtualenvs/django-calaccess-processed-data/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/palewire/.virtualenvs/django-calaccess-processed-data/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/palewire/.virtualenvs/django-calaccess-processed-data/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.IntegrityError: null value in column "transaction_id" violates not-null constraint
DETAIL:  Failing row contains (7097514, 583, 2012-09-12, null, , null, , IND, , , INGRASSIA, STEVEN, , GLENDALE, CA, 91208, INDEPENDENT STATE FARM OR ALLSTATE AGENT, INSURANCE AGENT, f, , , , , , , , , , , f, 200.00, 0.00, 50.00, 44134).
```

**Comment by palewire** [comment]
This is only happening on my laptop. I am going to assume something is screwed up there and move on.
