### ISSUE TITLE
Scrape error

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-processed-data#250]
```
DEBUG|19/Apr/2018 13:42:28|__init__|Loading Elections from scraped candidates
ERROR|19/Apr/2018 13:42:30|manage|Admin Command Error: /apps/django-calaccess-downloads-website/repo/manage.py updatedownloadswebsite --noinput --publish --verbosity=2
Traceback (most recent call last):
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/calaccess_processed_elections/proxies/calaccess_scraped/candidateelections.py", line 38, in get_ocd_election
    identifiers__identifier=self.scraped_id,
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
calaccess_processed_elections.proxies.opencivicdata.elections.elections.DoesNotExist: OCDElectionProxy matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/apps/django-calaccess-downloads-website/repo/manage.py", line 37, in <module>
    execute_from_command_line(sys.argv)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/apps/django-calaccess-downloads-website/repo/calaccess_website/management/commands/updatedownloadswebsite.py", line 37, in handle
    call_command('processcalaccessdata')
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/core/management/__init__.py", line 141, in call_command
    return command.execute(*args, **defaults)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/calaccess_processed/management/commands/processcalaccessdata.py", line 81, in handle
    self.load()
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/calaccess_processed/management/commands/processcalaccessdata.py", line 130, in load
    no_color=self.no_color,
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/core/management/__init__.py", line 141, in call_command
    return command.execute(*args, **defaults)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/calaccess_processed_elections/management/commands/processcalaccesselections.py", line 34, in handle
    self.load()
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/calaccess_processed_elections/management/commands/processcalaccesselections.py", line 67, in load
    call_command('loadocdcandidateelections', **options)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/core/management/__init__.py", line 141, in call_command
    return command.execute(*args, **defaults)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/calaccess_processed_elections/management/commands/loadocdcandidateelections.py", line 27, in handle
    self.load_from_proxy(ScrapedCandidateElectionProxy)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/calaccess_processed_elections/management/commands/__init__.py", line 38, in load_from_proxy
    ocd_election, ocd_created = scraped_election.get_or_create_ocd_election()
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/calaccess_processed_elections/proxies/calaccess_scraped/base.py", line 32, in get_or_create_ocd_election
    ocd_election = self.get_ocd_election()
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/calaccess_processed_elections/proxies/calaccess_scraped/candidateelections.py", line 42, in get_ocd_election
    if self.date:
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/calaccess_processed_elections/proxies/calaccess_scraped/candidateelections.py", line 112, in date
    self.date.year, self.election_type
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/calaccess_processed_elections/proxies/calaccess_scraped/candidateelections.py", line 112, in date
    self.date.year, self.election_type
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/calaccess_processed_elections/proxies/calaccess_scraped/candidateelections.py", line 112, in date
    self.date.year, self.election_type
  [Previous line repeated 462 more times]
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/calaccess_processed_elections/proxies/calaccess_scraped/candidateelections.py", line 100, in date
    name__icontains=self.parsed_name['type'],
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/db/models/query.py", line 397, in get
    num = len(clone)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/db/models/query.py", line 254, in __len__
    self._fetch_all()
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/db/models/query.py", line 1179, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1054, in execute_sql
    sql, params = self.as_sql()
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 460, in as_sql
    where, w_params = self.compile(self.where) if self.where is not None else ("", [])
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 391, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/db/models/sql/where.py", line 80, in as_sql
    sql, params = compiler.compile(child)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 391, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/db/models/sql/where.py", line 80, in as_sql
    sql, params = compiler.compile(child)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 391, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/db/models/lookups.py", line 355, in as_sql
    return super().as_sql(compiler, connection)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/db/models/lookups.py", line 160, in as_sql
    lhs_sql, params = self.process_lhs(compiler, connection)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/db/models/lookups.py", line 151, in process_lhs
    lhs_sql, params = super().process_lhs(compiler, connection, lhs)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/db/models/lookups.py", line 77, in process_lhs
    lhs = lhs.resolve_expression(compiler.query)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/db/models/expressions.py", line 243, in resolve_expression
    c = self.copy()
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/db/models/expressions.py", line 337, in copy
    return copy.copy(self)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/copy.py", line 106, in copy
    return _reconstruct(x, None, *rv)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/copy.py", line 274, in _reconstruct
    y = func(*args)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/copyreg.py", line 88, in __newobj__
    return cls.__new__(cls, *args)
RecursionError: maximum recursion depth exceeded
```

**Comment by palewire** [comment]
From the new production instance released yesterday

**Comment by palewire** [comment]
This appears to be within `self.load_from_proxy(ScrapedCandidateElectionProxy)` in `loadocdcandidateelections`.

**Comment by palewire** [comment]
This is cause by new special elections turning up in the scrape. Surprise.

**Comment by palewire** [comment]
Looks the 2018 Assembly 54 race is in the database twice in error. This could be a separate issue.

**Comment by palewire** [comment]
2018 Assembly 45 is also in there twice. Not good.

**Comment by palewire** [comment]
2018 Assembly 39 also in there twice.

**Comment by palewire** [comment]
2018 State Senate 29 needs to have a date added. I will toss that in and ship a new version.

**Comment by palewire** [comment]
This is clearly an issue with processing many of the new 2018 election. It seems to me that there is clearly a bug in our get_ocd_election method somewhere that is triggering these recursive errors. Even if errors are unavoidable on new elections, we need them to be clear. The looping has to stop or I will lose my mind.

**Comment by palewire** [comment]
After adding more special elections for this year, I see the error persists with the 2018 primary.

```bash
2018 PRIMARY (2018-06-05)

2018 SPECIAL RUNOFF (ASSEMBLY 45)
Traceback (most recent call last):
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/calaccess_processed_elections/proxies/calaccess_scraped/candidateelections.py", line 38, in get_ocd_election
    identifiers__identifier=self.scraped_id,
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
calaccess_processed_elections.proxies.opencivicdata.elections.elections.DoesNotExist: OCDElectionProxy matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 3, in <module>
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/calaccess_processed_elections/proxies/calaccess_scraped/candidateelections.py", line 42, in get_ocd_election
    if self.date:
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/calaccess_processed_elections/proxies/calaccess_scraped/candidateelections.py", line 111, in date
    return get_expected_election_date(self.date.year, self.election_type)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/calaccess_processed_elections/proxies/calaccess_scraped/candidateelections.py", line 111, in date
    return get_expected_election_date(self.date.year, self.election_type)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/calaccess_processed_elections/proxies/calaccess_scraped/candidateelections.py", line 111, in date
    return get_expected_election_date(self.date.year, self.election_type)
  [Previous line repeated 471 more times]
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/calaccess_processed_elections/proxies/calaccess_scraped/candidateelections.py", line 100, in date
    name__icontains=self.parsed_name['type'],
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/db/models/query.py", line 397, in get
    num = len(clone)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/db/models/query.py", line 254, in __len__
    self._fetch_all()
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/db/models/query.py", line 1179, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1054, in execute_sql
    sql, params = self.as_sql()
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 460, in as_sql
    where, w_params = self.compile(self.where) if self.where is not None else ("", [])
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 391, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/db/models/sql/where.py", line 80, in as_sql
    sql, params = compiler.compile(child)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 391, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/db/models/sql/where.py", line 80, in as_sql                                                                         [0/516]
    sql, params = compiler.compile(child)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 391, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/db/models/lookups.py", line 355, in as_sql
    return super().as_sql(compiler, connection)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/db/models/lookups.py", line 160, in as_sql
    lhs_sql, params = self.process_lhs(compiler, connection)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/db/models/lookups.py", line 151, in process_lhs
    lhs_sql, params = super().process_lhs(compiler, connection, lhs)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/db/models/lookups.py", line 77, in process_lhs
    lhs = lhs.resolve_expression(compiler.query)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/db/models/expressions.py", line 243, in resolve_expression
    c = self.copy()
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/db/models/expressions.py", line 337, in copy
    return copy.copy(self)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/copy.py", line 106, in copy
    return _reconstruct(x, None, *rv)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/copy.py", line 274, in _reconstruct
    y = func(*args)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/copyreg.py", line 88, in __newobj__
    return cls.__new__(cls, *args)
  File "/apps/django-calaccess-downloads-website/lib/python3.6/site-packages/django/utils/deconstruct.py", line 16, in __new__
    obj = super(klass, cls).__new__(cls)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by palewire** [comment]
Part of me wonders if the entire system of trying to process the scraped data is overcooked and we'd be better off providing an explicit list of elections ourselves.
