### ISSUE TITLE
RetentionContest fail

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-processed-data#255]
```Loading Retention Contests
Traceback (most recent call last):
  File "/home/palewire/Code/django-calaccess-processed-data/calaccess_processed_elections/management/commands/loadocdretentioncontests.py", line 99, in load
    identifiers__identifier=scraped_prop.scraped_id,
  File "/home/palewire/.virtualenvs/django-calaccess-processed-data/local/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/palewire/.virtualenvs/django-calaccess-processed-data/local/lib/python3.5/site-packages/django/db/models/query.py", line 399, in get
    self.model._meta.object_name
opencivicdata.elections.models.contests.ballot_measure.DoesNotExist: RetentionContest matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/home/palewire/.virtualenvs/django-calaccess-processed-data/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/palewire/.virtualenvs/django-calaccess-processed-data/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/palewire/.virtualenvs/django-calaccess-processed-data/local/lib/python3.5/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/palewire/.virtualenvs/django-calaccess-processed-data/local/lib/python3.5/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/palewire/Code/django-calaccess-processed-data/calaccess_processed/management/commands/processcalaccessdata.py", line 81, in handle
    self.load()
  File "/home/palewire/Code/django-calaccess-processed-data/calaccess_processed/management/commands/processcalaccessdata.py", line 130, in load
    no_color=self.no_color,
  File "/home/palewire/.virtualenvs/django-calaccess-processed-data/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 148, in call_command
    return command.execute(*args, **defaults)
  File "/home/palewire/.virtualenvs/django-calaccess-processed-data/local/lib/python3.5/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/palewire/Code/django-calaccess-processed-data/calaccess_processed_elections/management/commands/processcalaccesselections.py", line 34, in handle
    self.load()
  File "/home/palewire/Code/django-calaccess-processed-data/calaccess_processed_elections/management/commands/processcalaccesselections.py", line 80, in load
    call_command('loadocdretentioncontests', **options)
  File "/home/palewire/.virtualenvs/django-calaccess-processed-data/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 148, in call_command
    return command.execute(*args, **defaults)
  File "/home/palewire/.virtualenvs/django-calaccess-processed-data/local/lib/python3.5/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/palewire/Code/django-calaccess-processed-data/calaccess_processed_elections/management/commands/loadocdretentioncontests.py", line 31, in handle
    self.load()
  File "/home/palewire/Code/django-calaccess-processed-data/calaccess_processed_elections/management/commands/loadocdretentioncontests.py", line 103, in load
    ocd_contest = self.create_contest(scraped_prop, ocd_election)
  File "/home/palewire/Code/django-calaccess-processed-data/calaccess_processed_elections/management/commands/loadocdretentioncontests.py", line 48, in create_contest
    office = scraped_prop.name.split(' - ')[2].replace('DISTRICT ', '')
IndexError: list index out of range
```

**Comment by palewire** [comment]
The failing scraped name:

```
SENATE DISTRICT 29 - SPECIAL RECALL ELECTION
```
