### ISSUE TITLE
Travis Errors in OCD model implementation

### ISSUE THREAD

**Issue by gordonje** [california-civic-data-coalition/django-calaccess-processed-data#34]
Our tests are passing when I run them in my local env (Python 2.7.11, Django 1.10.5), but the [Travis build](https://travis-ci.org/california-civic-data-coalition/django-calaccess-processed-data) shows errors that are proving to be might persistent. The errors vary based on the job config.

**Comment by palewire** [comment]
Hmm. Is there a "jsonb" field in the models?

**Comment by gordonje** [comment]
@palewire yeah, that's the error I get with Python 2.7 config, both Django 1.9 and 1.10:

```
$ coverage run example/manage.py test calaccess_processed
Creating test database for alias 'default'...
Traceback (most recent call last):
  File "example/manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/commands/test.py", line 30, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/commands/test.py", line 74, in execute
    super(Command, self).execute(*args, **options)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/commands/test.py", line 90, in handle
    failures = test_runner.run_tests(test_labels)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/test/runner.py", line 532, in run_tests
    old_config = self.setup_databases()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/test/runner.py", line 482, in setup_databases
    self.parallel, **kwargs
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/test/runner.py", line 726, in setup_databases
    serialize=connection.settings_dict.get("TEST", {}).get("SERIALIZE", True),
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/db/backends/base/creation.py", line 70, in create_test_db
    run_syncdb=True,
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/__init__.py", line 119, in call_command
    return command.execute(*args, **defaults)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 200, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/db/migrations/executor.py", line 92, in migrate
    self._migrate_all_forwards(plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/db/migrations/executor.py", line 121, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/db/migrations/executor.py", line 198, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/db/migrations/migration.py", line 123, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/db/migrations/operations/models.py", line 59, in database_forwards
    schema_editor.create_model(model)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 284, in create_model
    self.execute(sql, params or None)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 110, in execute
    cursor.execute(sql, params)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: type "jsonb" does not exist
LINE 1: ...d_at" timestamp with time zone NOT NULL, "extras" jsonb NOT ...
```

**Comment by gordonje** [comment]
This is the error for Python 3, both Django 1.9.9 and 1.10.3:

```
$ coverage run example/manage.py test calaccess_processed
Creating test database for alias 'default'...
Traceback (most recent call last):
  File "example/manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/core/management/commands/test.py", line 30, in run_from_argv
    super(Command, self).run_from_argv(argv)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/core/management/commands/test.py", line 74, in execute
    super(Command, self).execute(*args, **options)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/core/management/commands/test.py", line 90, in handle
    failures = test_runner.run_tests(test_labels)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/test/runner.py", line 532, in run_tests
    old_config = self.setup_databases()
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/test/runner.py", line 482, in setup_databases
    self.parallel, **kwargs
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/test/runner.py", line 726, in setup_databases
    serialize=connection.settings_dict.get("TEST", {}).get("SERIALIZE", True),
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/db/backends/base/creation.py", line 70, in create_test_db
    run_syncdb=True,
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/core/management/__init__.py", line 119, in call_command
    return command.execute(*args, **defaults)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 89, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/db/migrations/executor.py", line 20, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/db/migrations/loader.py", line 170, in build_graph
    self.load_disk()
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/db/migrations/loader.py", line 105, in load_disk
    migration_module = import_module("%s.%s" % (module_name, migration_name))
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/travis/build/california-civic-data-coalition/django-calaccess-processed-data/calaccess_processed/migrations/0016_auto_20170119_1928.py", line 14, in <module>
    class Migration(migrations.Migration):
  File "/home/travis/build/california-civic-data-coalition/django-calaccess-processed-data/calaccess_processed/migrations/0016_auto_20170119_1928.py", line 151, in Migration
    ('id', calaccess_processed.models.opencivicdata.base.OCDIDField(ocd_type=b'jurisdiction', serialize=False, validators=[django.core.validators.RegexValidator(flags=32, message='ID must match ^ocd-jurisdiction/country:[a-z]{2}(/[^\\W\\d]+:[\\w.~-]+)*/\\w+$', regex=b'^ocd-jurisdiction/country:[a-z]{2}(/[^\\W\\d]+:[\\w.~-]+)*/\\w+$')])),
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/django/core/validators.py", line 50, in __init__
    raise TypeError("If the flags are set, regex must be a regular expression string.")
TypeError: If the flags are set, regex must be a regular expression string.
```

**Comment by palewire** [comment]
When did Postgres add JSONB support? Could it be a version issue there?

**Comment by gordonje** [comment]
@palewire Added in 1.9. jsonb is how Django implements its [JSONField](https://docs.djangoproject.com/en/1.10/ref/contrib/postgres/fields/#jsonfield).

**Comment by palewire** [comment]
Ah. If we drop Django 1.8 does that solve it?

**Comment by gordonje** [comment]
Already dropped Django 1.8 support.

Just learned that Travis-CI [uses postgres 9.1 by default](https://docs.travis-ci.com/user/database-setup/#Using-a-different-PostgreSQL-Version), so I locked us into 9.4. Seems to have fixed the jsonb error at least.

**Comment by palewire** [comment]
Interesting. I'm surprised TravisCI is that old. Good catch.

**Comment by gordonje** [comment]
Okay, now a different error is being thrown in the jobs configured with Python 2.7. At least now I'm able to re-create it local. You'll get it if you're on `csvkit>=1.0` and `django_calaccess_raw_data==1.4.7`.

I've [previously addressed](https://github.com/california-civic-data-coalition/django-calaccess-raw-data/commit/f9b7899f3af21d6b97b9b7d9909c0248f0dcf50b) in the raw-data app, but have not yet released the patch. Think I'll do that here in a bit, but first let's get this build working.

Looks like py2 jobs are error free with that last commit. Now about that regex error...

**Comment by gordonje** [comment]
![](http://i.giphy.com/vmJnAJo3P82Vq.gif)
