### ISSUE TITLE
OCD loading error

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-processed-data#43]
The first time I ran processcalaccessdata after pulling from master I got this error:

```python
$ python example/manage.py processcalaccessdata
Traceback (most recent call last):
  File "example/manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ben/.virtualenvs/django-calaccess-processed-data/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/ben/.virtualenvs/django-calaccess-processed-data/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ben/.virtualenvs/django-calaccess-processed-data/local/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ben/.virtualenvs/django-calaccess-processed-data/local/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "calaccess_processed/management/commands/processcalaccessdata.py", line 38, in handle
    self.load_ocd_models()
  File "calaccess_processed/management/commands/processcalaccessdata.py", line 127, in load_ocd_models
    Candidacy.objects.load_raw_data()
  File "calaccess_processed/models/opencivicdata/elections/candidacy.py", line 80, in load_raw_data
    classification='lower',
  File "/home/ben/.virtualenvs/django-calaccess-processed-data/local/lib/python2.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/ben/.virtualenvs/django-calaccess-processed-data/local/lib/python2.7/site-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
calaccess_processed.models.opencivicdata.people_orgs.DoesNotExist: Organization matching query does not exist.
```

**Comment by palewire** [comment]
I wonder if
