### ISSUE TITLE
mergepersonsbycontestandname crash

### ISSUE THREAD

**Issue by palewire** [california-civic-data-coalition/django-calaccess-processed-data#93]
```python
Merging Persons in same Contest with shared name
Merging 2 persons in STATE SENATE 26 (LIBERTARIAN) (in 2010 PRIMARY)
Traceback (most recent call last):
  File "example/manage.py", line 9, in <module>
    execute_from_command_line(sys.argv)
  File "/home/palewire/.virtualenvs/django-calaccess-processed-data/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/palewire/.virtualenvs/django-calaccess-processed-data/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/palewire/.virtualenvs/django-calaccess-processed-data/local/lib/python2.7/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/palewire/.virtualenvs/django-calaccess-processed-data/local/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "calaccess_processed/management/commands/loadocdmodels.py", line 27, in handle
    self.load()
  File "calaccess_processed/management/commands/loadocdmodels.py", line 61, in load
    call_command('mergepersonsbycontestandname', **options)
  File "/home/palewire/.virtualenvs/django-calaccess-processed-data/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 130, in call_command
    return command.execute(*args, **defaults)
  File "/home/palewire/.virtualenvs/django-calaccess-processed-data/local/lib/python2.7/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "calaccess_processed/management/commands/mergepersonsbycontestandname.py", line 34, in handle
    self.handle_group(group_q)
  File "calaccess_processed/management/commands/mergepersonsbycontestandname.py", line 140, in handle_group
    self.merge_persons([c.person for c in group_q.all()])
  File "calaccess_processed/management/commands/__init__.py", line 671, in merge_persons
    merge(keep, i)
  File "/home/palewire/.virtualenvs/django-calaccess-processed-data/src/python-opencivicdata/opencivicdata/merge.py", line 128, in merge
    diff = compute_diff(obj1, obj2)
  File "/home/palewire/.virtualenvs/django-calaccess-processed-data/src/python-opencivicdata/opencivicdata/merge.py", line 22, in compute_diff
    raise ValueError('cannot merge object with itself')
ValueError: cannot merge object with itself
```

**Comment by palewire** [comment]
After I flushed the OCD models this sorted itself out. What's that about?

**Comment by palewire** [comment]
This appears to be caused by rerunning the command that loads all OCD elections data a second time after a full processed run is complete. I was doing this as I experimented with correction candidate-party connections for our code rush. I don't know if it's a feature, a bug, or worth ignore. But I'm noting it here.

**Comment by palewire** [comment]
When I run it as part of the overall routine I instead see three mergers.

```
Duration: 0:12:21.628274
Merging Persons in same Contest with shared name
Merging 2 persons in ASSEMBLY 39 (in 2012 PRIMARY)
 - RICARDO BENITEZ
 - RICARDO BENITEZ
Merging 2 persons in ASSEMBLY 39 (in 2012 PRIMARY)
 - KEVIN J. SUSCAVAGE
 - KEVIN J. SUSCAVAGE
Merging 2 persons in ASSEMBLY 39 (in 2014 PRIMARY)
 - KEVIN J. SUSCAVAGE
 - KEVIN J. SUSCAVAGE
Done!
```
